baseURL = "http://gaertner.audio/"
languageCode = "en-us"
title = "Johannes Gärtner"
theme = "nix"

[menu]
  [[menu.header]]
    name = "About"
    weight = 0
    url = "/posts"

[params]
	FacebookID = "johannes.gaertner1991"
	Name = "Johannes Gärtner"
	HeaderUsername = "username"
	HeaderHostname = "hostname"
	Email = "johannes@gaertner.audio"
	About = "Hier Infotext"
	ProfilePicture = "/static/Pics/Profil.png"
