baseURL = "http://gaertner.audio/"
languageCode = "en-us"
title = "Johannes Gärtner"
theme = "mr.Hugo"

[params]
	# Metadaten Suchmaschinen
	#name = Johannes Gärtner
	#description = Tontechniker Berlin

	# Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #email = "your@email.com"

	[params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Johannes Gärtner"
        subtitle = "Tontechniker - Boom Operator - Set Assistant - Stagehand - B.o.A. Audio Production"
    
    [params.navigation]
        brand = "Top"

    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec orci lectus. Mauris suscipit nibh eu nulla tempus facilisis. Nulla facilisi. Nulla facilisi. Aenean condimentum ultrices iaculis. Cras id elementum nunc. Ut blandit consectetur nisi et mattis. In egestas tortor ut vehicula euismod. Aenean mollis dapibus nibh, sit amet dictum ex pellentesque sed. Nulla id turpis varius, porttitor elit et, luctus lacus. Aenean non fermentum magna. Donec pretium sollicitudin est. Pellentesque malesuada, ligula pretium accumsan laoreet, odio tortor faucibus felis, quis sollicitudin sapien mi vitae magna. Duis et cursus erat, vel aliquam lorem. Praesent lacinia nunc ac hendrerit cursus."
        right = "Fusce eleifend massa eu tortor molestie laoreet. Aliquam pretium accumsan urna, eget accumsan ex placerat ut. Suspendisse aliquam molestie enim ut aliquam. Mauris venenatis ultricies vestibulum. Etiam vel enim neque. Quisque ac molestie massa. Aliquam feugiat diam mauris, sit amet aliquam ligula tempor eu. Duis cursus euismod dui, vel ornare magna aliquam ut. Ut malesuada tortor tellus, et gravida mi sagittis vitae. In a efficitur sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut id lacus non nulla consectetur eleifend non id magna. Ut egestas fermentum pellentesque. Phasellus feugiat tristique est eget cursus."

        [params.about.button] #Auskommentiert im HTML
            text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"

     [params.portfolio]
         # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Informationen"

        [params.portfolio.modal]
            buttontext = "Close"
	
	[params.contact]
        title = "Kontakt"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Addresse"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Telefonnummer"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Nachricht"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Abschicken"

	##


	[params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Germany", "10409 Berlin", "Storkower Straße 13"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-envelope"
                link = "mailto:johannes@gaertner.audio"

            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link=  "//facebook.com/johannes.gaertner1991"

            [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com). Icons designed by [Prosymbols](https://www.flaticon.com/authors/prosymbols) from [Flaticon](https://www.flaticon.com)"
